version: '3.8'
services:
  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
  
  consumer_1:
    build: ./consumer_1
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
  
  consumer_2:
    build: ./consumer_2
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  consumer_3:
    build: ./consumer_3
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
